set(MASTER_THESIS_SEL4_IMAGES_DIR "${CMAKE_CURRENT_LIST_DIR}" CACHE STRING "")
mark_as_advanced(MASTER_THESIS_SEL4_IMAGES_DIR)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(master-thesis-sel4-images DEFAULT_MSG MASTER_THESIS_SEL4_IMAGES_DIR)
