set(MASTER_THESIS_IMAGES_FOR_SEL4_DIR "${CMAKE_CURRENT_LIST_DIR}" CACHE STRING "")
mark_as_advanced(MASTER_THESIS_IMAGES_FOR_SEL4_DIR)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(master-thesis-images DEFAULT_MSG MASTER_THESIS_IMAGES_FOR_SEL4_DIR)
